export const WORKTREE_CITIES: readonly string[] = [
  'tokyo',
  'osaka',
  'kyoto',
  'nagoya',
  'sapporo',
  'seoul',
  'busan',
  'beijing',
  'shanghai',
  'chengdu',
  'shenzhen',
  'taipei',
  'bangkok',
  'hanoi',
  'manila',
  'jakarta',
  'singapore',
  'delhi',
  'mumbai',
  'chennai',
  'bangalore',
  'kolkata',
  'dhaka',
  'karachi',
  'lahore',
  'kabul',
  'tehran',
  'baghdad',
  'damascus',
  'beirut',
  'jerusalem',
  'istanbul',
  'ankara',
  'dubai',
  'doha',
  'riyadh',
  'muscat',
  'cairo',
  'alexandria',
  'tunis',
  'tripoli',
  'algiers',
  'casablanca',
  'dakar',
  'accra',
  'lagos',
  'nairobi',
  'mombasa',
  'kampala',
  'khartoum',
  'harare',
  'luanda',
  'kinshasa',
  'london',
  'dublin',
  'edinburgh',
  'glasgow',
  'manchester',
  'liverpool',
  'cardiff',
  'belfast',
  'paris',
  'lyon',
  'marseille',
  'bordeaux',
  'madrid',
  'barcelona',
  'valencia',
  'seville',
  'lisbon',
  'porto',
  'rome',
  'milan',
  'naples',
  'venice',
  'florence',
  'turin',
  'berlin',
  'munich',
  'hamburg',
  'cologne',
  'frankfurt',
  'amsterdam',
  'rotterdam',
  'brussels',
  'antwerp',
  'vienna',
  'salzburg',
  'zurich',
  'geneva',
  'bern',
  'prague',
  'warsaw',
  'krakow',
  'budapest',
  'athens',
  'stockholm',
  'oslo',
  'bergen',
  'helsinki',
  'copenhagen',
  'reykjavik',
  'moscow',
  'kiev',
  'minsk',
  'sofia',
  'bucharest',
  'belgrade',
  'zagreb',
  'ljubljana',
  'tallinn',
  'riga',
  'vilnius',
  'toronto',
  'montreal',
  'vancouver',
  'ottawa',
  'calgary',
  'quebec',
  'halifax',
  'chicago',
  'boston',
  'seattle',
  'portland',
  'denver',
  'austin',
  'dallas',
  'houston',
  'miami',
  'atlanta',
  'nashville',
  'detroit',
  'phoenix',
  'minneapolis',
  'philadelphia',
  'baltimore',
  'cleveland',
  'pittsburgh',
  'milwaukee',
  'orlando',
  'memphis',
  'havana',
  'kingston',
  'panama',
  'lima',
  'quito',
  'bogota',
  'caracas',
  'brasilia',
  'salvador',
  'recife',
  'manaus',
  'santiago',
  'montevideo',
  'asuncion',
  'sydney',
  'melbourne',
  'brisbane',
  'adelaide',
  'perth',
  'canberra',
  'hobart',
  'auckland',
  'wellington',
  'christchurch',
  'suva',
  'honolulu',
  'anchorage',
];

export const WORKTREE_COLORS: readonly string[] = [
  '#b52e31',
  '#087CA7',
  '#42b883',
  '#ff3e00',
  '#f9e64f',
  '#5dc9e2',
  '#68217A',
  '#1857a4',
  '#eb5424',
  '#215732',
  '#832561',
  '#007fff',
  '#639',
  '#bd10e0',
  '#f48024',
];

export class WorktreeNamingUtils {
  static pickCity(taken: ReadonlySet<string>): string {
    const shuffled = shuffle(WORKTREE_CITIES);
    for (const city of shuffled) {
      if (!taken.has(city)) {
        return city;
      }
    }

    const base = shuffled[0];
    for (let suffix = 2; suffix < 1000; suffix++) {
      const candidate = `${base}-${suffix}`;
      if (!taken.has(candidate)) {
        return candidate;
      }
    }

    return `${base}-${Date.now()}`;
  }

  static pickColor(): string {
    const index = Math.floor(Math.random() * WORKTREE_COLORS.length);
    return WORKTREE_COLORS[index];
  }
}

function shuffle<T>(items: readonly T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
